### ISSUE TITLE
Revamp - Contact Us page.

### ISSUE THREAD

**Issue by JigmeT123** [JigmeT123/astrocredence#3]
You can beautify or make the current Contact Us page better. 
The creativity is all yours.

**Comment by DADDY-DOUBLESHOT** [comment]
Would like to work it ...

**Comment by JigmeT123** [comment]
> Would like to work on it ...

Sure will assign it to you

**Comment by varunsh17** [comment]
Would like to work upon it

**Comment by JigmeT123** [comment]
> Would like to work upon it 
> 
> 
 Sure go ahead

**Comment by varunsh17** [comment]
Working on it buddy will make pull request soon !

**Comment by JigmeT123** [comment]
> Hi @JigmeT123 Please assign it to me if no one is working on this issue.

sure @NitinNair89 go ahead.

**Comment by NitinNair89** [comment]
Hi @JigmeT123 
Why are we using `useForm()` custom hook when form validations can be done using react-material itself? Since we're already using the MUI package, I was of the opinion that we use that library throughout the application.
Thoughts?
