### ISSUE TITLE
Edit Navbar

### ISSUE THREAD

**Issue by Mitushi-23** [JigmeT123/astrocredence#5]
Navbar is not that much attractive.

**Comment by Mitushi-23** [comment]
Can I work on it?

**Comment by JigmeT123** [comment]
> Can I work on it? @JigmeT123 

Sure I will assign it to you

**Comment by Prajit-Sengupta** [comment]
Can i work on this?

**Comment by JigmeT123** [comment]
> Can i work on this?

sure I will assign this to you as well
